# Generated by Django 4.0.5 on 2022-07-06 11:18

import apps.support
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adverts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('category', models.CharField(choices=[('Дом', 'Дом'), ('Студия', 'Студия'), ('Квартира', 'Квартира'), ('Лофт', 'Лофт'), ('Коттедж', 'Коттедж'), ('Вилла', 'Вилла'), ('Дуплекс', 'Дуплекс'), ('Таунхаус', 'Таунхаус'), ('Пентхаус', 'Пентхаус'), ('Апартаменты', 'Апартаменты')], max_length=64, verbose_name='Тип жилья')),
                ('city', models.CharField(max_length=64, verbose_name='Город')),
                ('street', models.CharField(max_length=64, verbose_name='Улица')),
                ('home_number', models.CharField(max_length=8, verbose_name='Номер дома')),
                ('guest_count', models.IntegerField(verbose_name='Кол-во гостей')),
                ('bed_count', models.IntegerField(verbose_name='Кол-во кроватей')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
            },
        ),
        migrations.CreateModel(
            name='Comforts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comfort', models.CharField(max_length=255, verbose_name='Удобство')),
            ],
            options={
                'verbose_name': 'Удобство',
                'verbose_name_plural': 'Удобства',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=apps.support.my_awesome_upload_function, verbose_name='Путь')),
            ],
            options={
                'verbose_name': 'Картинка',
                'verbose_name_plural': 'Картинки',
            },
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_check_in', models.DateField(verbose_name='Дата заезда')),
                ('date_check_out', models.DateField(verbose_name='Дата выезда')),
                ('adult_count', models.IntegerField(verbose_name='Кол-во гостей')),
                ('child_count', models.IntegerField(verbose_name='Кол-во детей')),
                ('pet_count', models.IntegerField(verbose_name='Кол-во питомцев')),
            ],
            options={
                'verbose_name': 'Резервация',
                'verbose_name_plural': 'Резервации',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(verbose_name='Комментарий')),
                ('advert_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.adverts', verbose_name='Объявление')),
            ],
            options={
                'verbose_name': 'Резервация',
                'verbose_name_plural': 'Резервации',
            },
        ),
    ]
