# Generated by Django 4.0.5 on 2022-07-06 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='reservations',
            name='advert_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.adverts', verbose_name='Объявление'),
        ),
        migrations.AddField(
            model_name='reservations',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='images',
            name='advert_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.adverts'),
        ),
        migrations.AddField(
            model_name='adverts',
            name='comfort',
            field=models.ManyToManyField(to='core.comforts', verbose_name='Удобства'),
        ),
        migrations.AddField(
            model_name='adverts',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
    ]
